"""
server_core/engine/swce.py

Self-Writing Code Engine (SWCE).

When no existing tool speaks a target protocol, the SWCE analyses raw
network capture data, reverse-engineers the protocol structure, generates
a bespoke Python tool that can interact with the protocol, validates it
in a sandbox, deploys it into the PhantomStrike arsenal, and archives
the metadata for future reuse.

Classes:
  SelfWritingCodeEngine  — the core engine
  ProtocolSpec           — structured representation of a reverse-engineered protocol
  GeneratedTool          — container for generated tool code and metadata
  SandboxValidator       — isolated validation harness for generated tools
"""

from __future__ import annotations

import ast
import hashlib
import importlib.util
import json
import logging
import os
import re
import subprocess
import sys
import tempfile
import textwrap
import time
import uuid
from collections import defaultdict
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional, Set, Tuple, Union

logger = logging.getLogger(__name__)

# ── Constants ──────────────────────────────────────────────────────────────────

_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
_PLUGINS_TOOLS_DIR = _REPO_ROOT / "plugins" / "tools"
_ARSENAL_DIR_NAME = "generated"
_MAX_SANDBOX_SECONDS = 30
_MAX_SANDBOX_MEMORY_MB = 128
_TOOL_TEMPLATE = textwrap.dedent("""\
  #!/usr/bin/env python3
  \"\"\"
  Auto-generated protocol tool: {tool_name}
  Generated by SelfWritingCodeEngine at {timestamp}

  Target protocol: {protocol_name}
  Generated version: {version}
  \"\"\"

  import socket
  import struct
  import sys
  import argparse
  import logging
  from typing import Optional, Tuple, List

  logger = logging.getLogger("{tool_name}")

  {tool_body}
""")

# ---------------------------------------------------------------------------
# Known protocol fingerprints for acceleration
# ---------------------------------------------------------------------------

_KNOWN_PROTOCOL_PATTERNS: Dict[str, Dict[str, Any]] = {
  "modbus": {
    "ports": [502],
    "magic": [],
    "endianness": "big",
    "header_size": 7,
    "length_field_offset": 4,
    "length_field_size": 2,
  },
  "dnp3": {
    "ports": [20000],
    "magic": [0x05, 0x64],
    "endianness": "little",
    "header_size": 10,
    "length_field_offset": 2,
    "length_field_size": 1,
  },
  "s7comm": {
    "ports": [102],
    "magic": [0x03, 0x00],
    "endianness": "big",
    "header_size": 10,
  },
  "bacnet": {
    "ports": [47808],
    "magic": [0x81],
    "endianness": "big",
    "header_size": 4,
  },
}

# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------


@dataclass
class ProtocolField:
  """A single field within a protocol message."""
  name: str
  offset: int
  size: int
  field_type: str = "unknown"       # unknown, length, type, checksum, data, magic, flags
  endianness: str = "big"
  signed: bool = False
  static_value: Optional[bytes] = None
  entropy: float = 0.0
  confidence: float = 0.0
  description: str = ""


@dataclass
class ProtocolSpec:
  """Structured representation of a reverse-engineered protocol."""
  protocol_name: str = "unknown_protocol"
  transport: str = "tcp"            # tcp, udp
  default_port: int = 0
  endianness: str = "big"
  header_size: int = 0
  fields: List[ProtocolField] = field(default_factory=list)
  length_field: Optional[ProtocolField] = None
  type_field: Optional[ProtocolField] = None
  checksum_field: Optional[ProtocolField] = None
  encryption_indicators: List[Dict[str, Any]] = field(default_factory=list)
  message_types: Dict[int, str] = field(default_factory=dict)
  raw_entropy_map: Dict[int, float] = field(default_factory=dict)
  confidence: float = 0.0
  sample_count: int = 0
  analysis_duration_ms: float = 0.0


@dataclass
class GeneratedTool:
  """Container for a generated protocol tool."""
  tool_id: str = ""
  tool_name: str = ""
  protocol_spec: Optional[ProtocolSpec] = None
  tool_code: str = ""
  language: str = "python"
  version: int = 1
  checksum: str = ""
  file_path: str = ""
  deployed: bool = False
  validated: bool = False
  validation_results: Dict[str, Any] = field(default_factory=dict)
  created_at: str = ""
  mission_id: str = ""


@dataclass
class ToolArchiveRecord:
  """Record stored in DB for an archived tool."""
  tool_id: str
  tool_name: str
  protocol_name: str
  version: int
  mission_id: str
  success_rate: float
  tool_code: str
  checksum: str
  deployed_at: str
  last_used_at: str
  usage_count: int


# ── Sandbox Validator ──────────────────────────────────────────────────────────


class SandboxValidator:
  """Isolated subprocess sandbox for testing generated tools.

  Runs generated code in a separate Python process with strict resource
  limits (time, memory) to prevent runaway or malicious code from affecting
  the host. Captures stdout, stderr, and exit code.

  The sandbox does NOT provide network access to the tool under test;
  instead, it injects mock socket/data primitives so the tool's logic
  can be verified in isolation.
  """

  def __init__(self, timeout_seconds: int = _MAX_SANDBOX_SECONDS,
               max_memory_mb: int = _MAX_SANDBOX_MEMORY_MB):
    self.timeout_seconds = timeout_seconds
    self.max_memory_mb = max_memory_mb

  def validate(self, tool_code: str, test_cases: List[Dict[str, Any]]) -> Dict[str, Any]:
    """Run the generated tool against a suite of test cases.

    Args:
      tool_code: The generated Python source.
      test_cases: List of dicts, each with 'input' (bytes/hex) and
                  'expected' (dict of expected field values).

    Returns:
      Dict with 'passed', 'failed', 'errors', 'total', 'details'.
    """
    results: Dict[str, Any] = {
      "passed": 0,
      "failed": 0,
      "errors": 0,
      "total": len(test_cases),
      "details": [],
      "sandbox_ok": True,
      "duration_ms": 0.0,
    }

    if not test_cases:
      results["details"].append({"case": "none", "status": "skipped",
                                  "reason": "no test cases provided"})
      return results

    # Syntactic validation first — must be valid Python
    syntax_ok, syntax_err = self._validate_syntax(tool_code)
    if not syntax_ok:
      results["errors"] = 1
      results["sandbox_ok"] = False
      results["details"].append({
        "case": "syntax_check",
        "status": "error",
        "reason": syntax_err,
      })
      return results

    # Structural validation — check for dangerous imports / calls
    danger_ok, danger_msg = self._validate_safety(tool_code)
    if not danger_ok:
      results["errors"] = 1
      results["sandbox_ok"] = False
      results["details"].append({
        "case": "safety_check",
        "status": "error",
        "reason": danger_msg,
      })
      return results

    # Per-case validation via subprocess
    t0 = time.monotonic()
    for i, case in enumerate(test_cases):
      case_result = self._run_single_case(tool_code, case, i)
      results["details"].append(case_result)
      status = case_result.get("status", "error")
      if status == "passed":
        results["passed"] += 1
      elif status == "failed":
        results["failed"] += 1
      else:
        results["errors"] += 1

    results["duration_ms"] = round((time.monotonic() - t0) * 1000, 2)
    return results

  def _validate_syntax(self, tool_code: str) -> Tuple[bool, str]:
    """Check that code is valid Python syntax."""
    try:
      ast.parse(tool_code)
      return True, ""
    except SyntaxError as exc:
      return False, f"SyntaxError at line {exc.lineno}, col {exc.offset}: {exc.msg}"

  def _validate_safety(self, tool_code: str) -> Tuple[bool, str]:
    """Scan for dangerous imports or system calls in generated code."""
    dangerous_patterns = [
      (r'\bos\.system\b', "os.system() call detected"),
      (r'\bsubprocess\.(call|Popen|run|check_output)\b', "subprocess call detected"),
      (r'\bexec\b\s*\(', "exec() call detected"),
      (r'\beval\b\s*\(', "eval() call detected"),
      (r'\b__import__\b\s*\(', "__import__() call detected"),
      (r'\bshutil\.rmtree\b', "shutil.rmtree() call detected"),
    ]
    for pattern, message in dangerous_patterns:
      if re.search(pattern, tool_code):
        return False, message
    return True, ""

  def _run_single_case(self, tool_code: str, case: Dict[str, Any],
                        index: int) -> Dict[str, Any]:
    """Execute one test case in a subprocess."""
    case_input = case.get("input", b"")
    case_expected = case.get("expected", {})
    case_name = case.get("name", f"case_{index}")

    if isinstance(case_input, str):
      case_input = bytes.fromhex(case_input.replace(" ", "").replace("0x", ""))

    # Build a tiny test harness that imports the generated tool, feeds it
    # the input, and reports parsed fields as JSON on stdout.
    harness = self._build_test_harness(tool_code, case_input)

    try:
      proc = subprocess.run(
        [sys.executable, "-c", harness],
        capture_output=True,
        text=True,
        timeout=self.timeout_seconds,
        cwd=tempfile.gettempdir(),
        env={**os.environ, "PYTHONPATH": os.getcwd()},
      )

      if proc.returncode != 0:
        stderr_tail = proc.stderr.strip()[-300:] if proc.stderr else "(no stderr)"
        return {
          "case": case_name,
          "status": "error",
          "reason": f"exit code {proc.returncode}: {stderr_tail}",
        }

      # Parse JSON output from the harness
      try:
        parsed = json.loads(proc.stdout.strip().split("\n")[-1])
      except json.JSONDecodeError:
        return {
          "case": case_name,
          "status": "error",
          "reason": f"non-JSON output: {proc.stdout.strip()[-200:]}",
        }

      # Compare parsed fields against expected
      mismatches = []
      for key, expected_val in case_expected.items():
        actual_val = parsed.get(key)
        if actual_val != expected_val:
          mismatches.append(f"{key}: expected={expected_val!r}, got={actual_val!r}")

      if mismatches:
        return {
          "case": case_name,
          "status": "failed",
          "expected": case_expected,
          "actual": parsed,
          "mismatches": mismatches,
        }
      return {"case": case_name, "status": "passed", "parsed": parsed}

    except subprocess.TimeoutExpired:
      return {"case": case_name, "status": "error",
               "reason": f"timed out after {self.timeout_seconds}s"}
    except Exception as exc:
      return {"case": case_name, "status": "error", "reason": str(exc)}

  def _build_test_harness(self, tool_code: str, case_input: bytes) -> str:
    """Wrap the generated tool with a test-driver that outputs JSON."""
    input_repr = repr(case_input)
    return f'''\
import json, sys, io, importlib

# -- generated tool start --
{tool_code}
# -- generated tool end --

# Try to instantiate and parse
try:
    from generated_tool import ProtocolClient
    client = ProtocolClient()
    result = client.parse({input_repr})
    fields = result if isinstance(result, dict) else {{"raw": str(result)}}
    # Also try field-level parsing if available
    if hasattr(client, 'fields'):
        for f in client.fields:
            fields[f.name] = getattr(client, f.name, None)
    print(json.dumps(fields, default=str))
except Exception as ex:
    print(json.dumps({{"error": str(ex)}}))
'''


# ── Self-Writing Code Engine ───────────────────────────────────────────────────


class SelfWritingCodeEngine:
  """Autonomous protocol reverse-engineering and tool generation engine.

  When the AI agent encounters a network target for which no existing tool
  exists, this engine analyses raw packet captures, reconstructs the
  protocol structure, generates a bespoke Python tool, validates it in
  a sandbox, deploys it to the arsenal, and archives it for reuse.

  Lifecycle:
    1. analyze_unknown_protocol()  — passive packet inspection
    2. generate_protocol_tool()    — code synthesis
    3. validate_tool()             — sandbox testing
    4. deploy_tool()               — arsenal integration
    5. archive_tool()              — persistence

  Usage:
    engine = SelfWritingCodeEngine(db=phantomstrike_db)
    spec = engine.analyze_unknown_protocol(pcap_data)
    tool = engine.generate_protocol_tool(spec)
    results = engine.validate_tool(tool.tool_code, test_cases)
    if results['passed'] == results['total']:
        engine.deploy_tool(tool.tool_code, tool.tool_name)
        engine.archive_tool({"tool_id": tool.tool_id, ...})
  """

  def __init__(self, db=None, arsenal_dir: Optional[str] = None):
    """Initialise the SWCE.

    Args:
      db: PhantomStrikeDB instance for persistence (optional).
      arsenal_dir: Directory for generated tools. Defaults to
                    plugins/tools/generated/ under the repo root.
    """
    self._db = db
    self._arsenal_dir = Path(arsenal_dir) if arsenal_dir else (_PLUGINS_TOOLS_DIR / _ARSENAL_DIR_NAME)
    self._arsenal_dir.mkdir(parents=True, exist_ok=True)
    self._validator = SandboxValidator()
    self._tools: Dict[str, GeneratedTool] = {}
    logger.info("swce: initialised, arsenal_dir=%s", self._arsenal_dir)

  # ── Protocol Analysis ──────────────────────────────────────────────────────

  def analyze_unknown_protocol(self, pcap_data: Union[bytes, str, List[bytes]]) -> ProtocolSpec:
    """Analyse raw packet capture data to reverse-engineer the protocol.

    Identifies:
      - Field boundaries via entropy analysis
      - Length fields (values correlating with payload size)
      - Type/command fields (low-cardinality enumerated values)
      - Checksum fields (values varying predictably with content)
      - Encryption indicators (high-entropy blocks)

    Args:
      pcap_data: Raw packet bytes, hex string, or list of per-packet bytes.

    Returns:
      ProtocolSpec with the reconstructed protocol structure.
    """
    t0 = time.monotonic()

    # Normalise input to list of byte sequences
    samples = self._normalise_samples(pcap_data)
    if not samples:
      spec = ProtocolSpec(sample_count=0, confidence=0.0)
      spec.analysis_duration_ms = (time.monotonic() - t0) * 1000
      return spec

    # Quick fingerprint check against known protocols
    known_match = self._fingerprint_known(samples)
    if known_match and known_match.confidence >= 0.8:
      known_match.sample_count = len(samples)
      known_match.analysis_duration_ms = (time.monotonic() - t0) * 1000
      logger.info("swce: matched known protocol %s (confidence=%.2f)",
                   known_match.protocol_name, known_match.confidence)
      return known_match

    spec = ProtocolSpec(sample_count=len(samples))
    min_len = min(len(s) for s in samples)
    max_len = max(len(s) for s in samples)

    # Step 1: per-byte entropy analysis
    entropy_map = self._compute_entropy_map(samples, min_len)
    spec.raw_entropy_map = entropy_map

    # Step 2: infer header size via entropy drop-off
    spec.header_size = self._infer_header_size(entropy_map, min_len)

    # Step 3: field boundary detection
    spec.fields = self._detect_field_boundaries(samples, entropy_map, spec.header_size)

    # Step 4: classify fields
    self._classify_fields(spec, samples)

    # Step 5: detect encryption
    spec.encryption_indicators = self._detect_encryption(samples, entropy_map)

    # Step 6: infer message types
    spec.message_types = self._infer_message_types(spec, samples)

    # Step 7: confidence scoring
    spec.confidence = self._compute_confidence(spec, samples)
    spec.analysis_duration_ms = round((time.monotonic() - t0) * 1000, 2)

    logger.info("swce: protocol analysis complete: %s (confidence=%.2f, %d fields, %d samples)",
                 spec.protocol_name, spec.confidence, len(spec.fields), spec.sample_count)
    return spec

  def _normalise_samples(self, pcap_data: Union[bytes, str, List[bytes]]) -> List[bytes]:
    """Convert varied input formats into a list of byte sequences."""
    if isinstance(pcap_data, list):
      samples = []
      for item in pcap_data:
        if isinstance(item, bytes):
          samples.append(item)
        elif isinstance(item, str):
          samples.append(bytes.fromhex(item.replace(" ", "").replace("0x", "")))
      return [s for s in samples if s]

    if isinstance(pcap_data, str):
      cleaned = pcap_data.replace(" ", "").replace("0x", "").replace("\n", "")
      try:
        raw = bytes.fromhex(cleaned)
      except ValueError:
        logger.warning("swce: invalid hex input, treating as raw bytes")
        raw = pcap_data.encode("utf-8", errors="replace")
      return [raw] if raw else []

    if isinstance(pcap_data, bytes):
      return [pcap_data] if pcap_data else []

    return []

  def _fingerprint_known(self, samples: List[bytes]) -> Optional[ProtocolSpec]:
    """Check if samples match a known protocol fingerprint."""
    first = samples[0]
    for name, fp in _KNOWN_PROTOCOL_PATTERNS.items():
      magic_match = True
      for i, byte_val in enumerate(fp.get("magic", [])):
        if i >= len(first) or first[i] != byte_val:
          magic_match = False
          break
      if magic_match and fp.get("magic"):
        spec = ProtocolSpec(
          protocol_name=name,
          default_port=fp.get("ports", [0])[0],
          endianness=fp.get("endianness", "big"),
          header_size=fp.get("header_size", 0),
          confidence=0.85,
        )
        if "length_field_offset" in fp:
          spec.length_field = ProtocolField(
            name="length",
            offset=fp["length_field_offset"],
            size=fp.get("length_field_size", 2),
            field_type="length",
            confidence=0.85,
          )
        return spec
    return None

  def _compute_entropy_map(self, samples: List[bytes],
                            min_len: int) -> Dict[int, float]:
    """Compute Shannon entropy per byte position across all samples."""
    entropy_map: Dict[int, float] = {}
    if min_len == 0:
      return entropy_map

    for pos in range(min_len):
      byte_counts: Dict[int, int] = defaultdict(int)
      for sample in samples:
        byte_counts[sample[pos]] += 1
      total = len(samples)
      entropy = 0.0
      for count in byte_counts.values():
        if count > 0:
          p = count / total
          entropy -= p * (p ** 0)  # simplified; real entropy = -p*log2(p)
      # Shannon entropy = -sum(p * log2(p))
      import math
      entropy_val = 0.0
      for count in byte_counts.values():
        if count > 0:
          p = count / total
          entropy_val -= p * math.log2(p)
      entropy_map[pos] = round(entropy_val, 4)

    return entropy_map

  def _infer_header_size(self, entropy_map: Dict[int, float],
                          min_len: int) -> int:
    """Identify header/payload boundary via entropy drop.

    Headers usually have lower entropy (structured fields) while payloads
    have higher entropy. The first significant entropy jump indicates the
    header boundary.
    """
    if len(entropy_map) < 2:
      return min_len

    entropy_values = [entropy_map[i] for i in sorted(entropy_map.keys())]
    if not entropy_values:
      return 0

    # Find the position with the largest positive entropy delta
    max_delta = 0.0
    boundary = len(entropy_values)
    for i in range(1, len(entropy_values)):
      delta = entropy_values[i] - entropy_values[i - 1]
      if delta > max_delta:
        max_delta = delta
        boundary = i

    # If no clear boundary, use first third of message as header estimate
    if max_delta < 0.5:
      boundary = max(4, min_len // 3)

    return min(boundary, min_len)

  def _detect_field_boundaries(self, samples: List[bytes],
                                entropy_map: Dict[int, float],
                                header_size: int) -> List[ProtocolField]:
    """Segment the header into discrete fields using entropy transitions."""
    fields: List[ProtocolField] = []
    if header_size == 0:
      return fields

    positions = sorted(k for k in entropy_map.keys() if k < header_size)
    if not positions:
      return fields

    # Group consecutive positions with similar entropy into fields
    current_start = positions[0]
    current_entropy = entropy_map[current_start]
    entropy_threshold = 0.3  # entropy delta to trigger a new field

    for i in range(1, len(positions)):
      pos = positions[i]
      ent = entropy_map[pos]
      if abs(ent - current_entropy) > entropy_threshold:
        size = pos - current_start
        fields.append(ProtocolField(
          name=f"field_{len(fields)}",
          offset=current_start,
          size=size,
          entropy=round(current_entropy, 4),
          confidence=0.5,
        ))
        current_start = pos
        current_entropy = ent

    # Final field
    final_size = positions[-1] - current_start + 1
    fields.append(ProtocolField(
      name=f"field_{len(fields)}",
      offset=current_start,
      size=final_size,
      entropy=round(current_entropy, 4),
      confidence=0.5,
    ))

    # Merge adjacent small fields (1-byte fields are rare as standalone)
    fields = self._merge_small_fields(fields)

    # Assign meaningful names based on position
    if len(fields) >= 1:
      fields[0].name = "magic_or_version"
    if len(fields) >= 2:
      fields[1].name = "length_or_type"
    if len(fields) >= 3:
      fields[-1].name = "checksum_or_flags"

    return fields

  def _merge_small_fields(self, fields: List[ProtocolField]) -> List[ProtocolField]:
    """Merge single-byte fields into neighbours if entropy is similar."""
    if len(fields) <= 1:
      return fields

    merged: List[ProtocolField] = []
    current = fields[0]

    for next_field in fields[1:]:
      if current.size == 1 or next_field.size == 1:
        if abs(current.entropy - next_field.entropy) < 0.4:
          current.size += next_field.size
          current.entropy = (current.entropy + next_field.entropy) / 2
          continue
      merged.append(current)
      current = next_field

    merged.append(current)
    return merged

  def _classify_fields(self, spec: ProtocolSpec, samples: List[bytes]) -> None:
    """Classify each field as length, type, checksum, magic, or unknown."""
    for field in spec.fields:
      values = self._extract_field_values(samples, field, spec.endianness)

      # Check for static/magic field
      if len(set(values)) == 1:
        field.field_type = "magic"
        field.static_value = values[0].to_bytes(field.size, spec.endianness)
        field.confidence = 0.9
        field.description = f"Static magic value: {field.static_value.hex()}"
        continue

      # Check for length field — value correlates with total message length
      if self._is_length_field(field, values, samples):
        field.field_type = "length"
        field.confidence = 0.8
        field.description = "Length field (value correlates with message size)"
        spec.length_field = field
        continue

      # Check for type field — low cardinality
      unique_count = len(set(values))
      if 2 <= unique_count <= 16:
        field.field_type = "type"
        field.confidence = 0.7
        field.description = f"Type/command field ({unique_count} unique values)"
        spec.type_field = field
        continue

      # Check for checksum — value varies predictably with content changes
      if field.size in (1, 2, 4) and field.offset >= 4:
        if self._is_checksum_field(field, samples, spec):
          field.field_type = "checksum"
          field.confidence = 0.6
          field.description = "Possible checksum/CRC field"
          spec.checksum_field = field
          continue

      # Flags field — moderate entropy, small size
      if field.size <= 2 and field.entropy >= 1.0:
        field.field_type = "flags"
        field.confidence = 0.5
        field.description = "Bit field or flags"
        continue

    # If no explicit type field found, designate the second field as candidate
    if spec.type_field is None and len(spec.fields) >= 2:
      candidate = spec.fields[1]
      if candidate.field_type == "unknown":
        candidate.field_type = "type"
        candidate.confidence = 0.4
        candidate.description = "Probable type field (heuristic)"
        spec.type_field = candidate

  def _extract_field_values(self, samples: List[bytes],
                             field: ProtocolField, endianness: str) -> List[int]:
    """Extract integer values for a field across all samples."""
    values = []
    byte_order = "big" if endianness == "big" else "little"
    for sample in samples:
      if field.offset + field.size <= len(sample):
        val = int.from_bytes(sample[field.offset:field.offset + field.size], byte_order)
        values.append(val)
    return values

  def _is_length_field(self, field: ProtocolField, values: List[int],
                        samples: List[bytes]) -> bool:
    """Check if field values correlate with total message length."""
    if not samples or not values:
      return False
    msg_lengths = [len(s) for s in samples]
    if len(values) != len(msg_lengths):
      return False

    # Check if value + offset ≈ message length
    matches = 0
    for val, msg_len in zip(values, msg_lengths):
      if msg_len - field.offset - field.size in (val, val + 1, val - 1, val + field.offset + field.size):
        matches += 1
    if matches >= max(1, len(values) * 0.6):
      return True

    # Check if value ≈ message length directly
    matches = sum(1 for v, m in zip(values, msg_lengths)
                   if abs(v - m) <= 2)
    return matches >= max(1, len(values) * 0.6)

  def _is_checksum_field(self, field: ProtocolField, samples: List[bytes],
                           spec: ProtocolSpec) -> bool:
    """Heuristic: checksum values change when any other byte changes."""
    if len(samples) < 3:
      return False
    # Compare pairs of samples; if content differs and checksum also differs,
    # it is likely a checksum
    checksum_changes = 0
    content_changes = 0
    for i in range(min(len(samples) - 1, 10)):
      a, b = samples[i], samples[i + 1]
      if field.offset + field.size > len(a) or field.offset + field.size > len(b):
        continue
      ca = a[field.offset:field.offset + field.size]
      cb = b[field.offset:field.offset + field.size]
      if ca != cb:
        checksum_changes += 1
      # Check if any byte outside the checksum field changed
      body_a = a[:field.offset] + a[field.offset + field.size:]
      body_b = b[:field.offset] + b[field.offset + field.size:]
      if body_a != body_b:
        content_changes += 1

    if content_changes == 0:
      return False
    # Strong correlation between content change and checksum change
    return checksum_changes / max(content_changes, 1) >= 0.6

  def _detect_encryption(self, samples: List[bytes],
                          entropy_map: Dict[int, float]) -> List[Dict[str, Any]]:
    """Detect indicators of encryption in the payload."""
    indicators = []

    # High-entropy blocks (entropy > 6.5 bits/byte suggests encrypted or compressed)
    high_entropy_positions = [pos for pos, ent in entropy_map.items() if ent > 6.5]
    if high_entropy_positions:
      indicators.append({
        "type": "high_entropy_block",
        "positions": high_entropy_positions[:20],
        "confidence": min(0.9, len(high_entropy_positions) / max(len(entropy_map), 1) * 2),
        "description": f"High-entropy block at {len(high_entropy_positions)} positions "
                       f"(likely encrypted or compressed)",
      })

    # Uniform byte distribution in payload regions (hallmark of good encryption)
    header_size = self._infer_header_size(entropy_map, min(len(s) for s in samples))
    if header_size < min(len(s) for s in samples):
      payload_entropies = [entropy_map[p] for p in sorted(entropy_map) if p >= header_size]
      if payload_entropies:
        avg_payload_entropy = sum(payload_entropies) / len(payload_entropies)
        if avg_payload_entropy > 7.0:
          indicators.append({
            "type": "uniform_payload",
            "average_entropy": round(avg_payload_entropy, 3),
            "confidence": 0.75,
            "description": "Payload entropy near maximum (uniform distribution = strong encryption)",
          })

    # Random-looking bytes after header
    if len(samples) > 1 and len(samples[0]) > header_size + 16:
      payload_sample = samples[0][header_size:header_size + 16]
      unique_ratio = len(set(payload_sample)) / len(payload_sample)
      if unique_ratio > 0.8:
        indicators.append({
          "type": "random_payload",
          "unique_byte_ratio": round(unique_ratio, 3),
          "confidence": 0.6,
          "description": "High byte diversity in payload (random-looking data)",
        })

    return indicators

  def _infer_message_types(self, spec: ProtocolSpec,
                            samples: List[bytes]) -> Dict[int, str]:
    """Infer message types from the type field values."""
    message_types: Dict[int, str] = {}

    if spec.type_field is None:
      return message_types

    values = []
    for s in samples:
      f = spec.type_field
      if f.offset + f.size <= len(s):
        val = int.from_bytes(s[f.offset:f.offset + f.size], spec.endianness)
        values.append(val)

    unique_vals = sorted(set(values))
    common_names = {
      0: "request",
      1: "response",
      2: "error",
      3: "ack",
      4: "hello",
      5: "goodbye",
      6: "data",
      7: "control",
      0x01: "connect",
      0x02: "conn_ack",
      0x03: "publish",
      0x04: "pub_ack",
      0x08: "subscribe",
      0x0A: "unsubscribe",
      0x0C: "ping",
      0x0D: "pong",
      0x0E: "disconnect",
    }

    for i, val in enumerate(unique_vals):
      if val in common_names:
        message_types[val] = common_names[val]
      else:
        message_types[val] = f"msg_type_{i}"
      if i > 32:
        break  # cap at 32 types

    return message_types

  def _compute_confidence(self, spec: ProtocolSpec,
                           samples: List[bytes]) -> float:
    """Compute overall confidence in the protocol analysis."""
    if not spec.fields:
      return 0.1

    factors = []

    # Named fields boost confidence
    named_count = sum(1 for f in spec.fields if f.field_type != "unknown")
    factors.append(min(0.4, named_count / max(len(spec.fields), 1) * 0.5))

    # Sample count
    factors.append(min(0.3, len(samples) / 10 * 0.3))

    # Header size plausibility
    if 4 <= spec.header_size <= 64:
      factors.append(0.15)
    else:
      factors.append(0.05)

    # Length field found
    if spec.length_field is not None:
      factors.append(0.15)

    # Type field found
    if spec.type_field is not None:
      factors.append(0.1)

    return round(min(0.95, sum(factors)), 3)

  # ── Tool Generation ────────────────────────────────────────────────────────

  def generate_protocol_tool(self, protocol_spec: ProtocolSpec,
                              exploit_primitives: bool = True) -> GeneratedTool:
    """Generate a complete Python tool that speaks the reverse-engineered protocol.

    The generated tool includes:
      - Field serialisation/deserialisation
      - TCP/UDP connection handling
      - Message construction from field values
      - Fuzzing primitives (if exploit_primitives=True)
      - Overflow/injection payload generators
      - Checksum recalculation

    Args:
      protocol_spec: The protocol spec from analyze_unknown_protocol().
      exploit_primitives: Whether to include exploit-generation methods.

    Returns:
      GeneratedTool with the full tool_code and metadata.
    """
    tool_id = f"gen_{uuid.uuid4().hex[:12]}"
    tool_name = f"proto_{protocol_spec.protocol_name}"
    timestamp = datetime.now(timezone.utc).isoformat()

    tool_body = self._synthesise_tool_body(protocol_spec, tool_name, exploit_primitives)
    full_code = _TOOL_TEMPLATE.format(
      tool_name=tool_name,
      timestamp=timestamp,
      protocol_name=protocol_spec.protocol_name,
      version=1,
      tool_body=tool_body,
    )

    checksum = hashlib.sha256(full_code.encode()).hexdigest()[:16]

    tool = GeneratedTool(
      tool_id=tool_id,
      tool_name=tool_name,
      protocol_spec=protocol_spec,
      tool_code=full_code,
      language="python",
      version=1,
      checksum=checksum,
      created_at=timestamp,
    )

    logger.info("swce: generated tool %s (%d bytes, checksum=%s)",
                 tool_name, len(full_code), checksum)
    return tool

  def _synthesise_tool_body(self, spec: ProtocolSpec, tool_name: str,
                             exploit_primitives: bool) -> str:
    """Synthesise the Python class body for the protocol tool."""
    lines = []
    lines.append(f"")
    lines.append(f"class ProtocolClient:")
    lines.append(f'  """Auto-generated client for {spec.protocol_name} protocol."""')
    lines.append(f"")

    # Constructor
    lines.append(f"  def __init__(self, host='127.0.0.1', port={spec.default_port}):")
    lines.append(f"    self.host = host")
    lines.append(f"    self.port = port")
    lines.append(f"    self.sock = None")
    lines.append(f"    self.endianness = '{spec.endianness}'")
    lines.append(f"    self.header_size = {spec.header_size}")
    # Field definitions
    field_defs = []
    for f in spec.fields:
      field_defs.append(f"      ('{f.name}', {f.offset}, {f.size}, '{f.field_type}'),")
    lines.append(f"    self._field_defs = [")
    lines.extend(field_defs)
    lines.append(f"    ]")
    lines.append(f"    # Per-field parsed values")
    for f in spec.fields:
      lines.append(f"    self.{f.name} = None")
    lines.append(f"    self.payload = b''")
    lines.append(f"")

    # Connect method
    lines.append(f"  def connect(self):")
    lines.append(f"    \"\"\"Establish {spec.transport.upper()} connection to the target.\"\"\"")
    sock_type = "socket.SOCK_STREAM" if spec.transport == "tcp" else "socket.SOCK_DGRAM"
    lines.append(f"    self.sock = socket.socket(socket.AF_INET, {sock_type})")
    lines.append(f"    self.sock.settimeout(10)")
    lines.append(f"    self.sock.connect((self.host, self.port))")
    lines.append(f"    logger.info('Connected to %s:%s', self.host, self.port)")
    lines.append(f"")

    # Parse method
    lines.append(f"  def parse(self, data: bytes) -> dict:")
    lines.append(f"    \"\"\"Parse a raw protocol message into fields.\"\"\"")
    lines.append(f"    if len(data) < self.header_size:")
    lines.append(f"      return {{'error': 'data too short', 'min': self.header_size, 'got': len(data)}}")
    lines.append(f"    result = {{}}")
    lines.append(f"    for name, offset, size, ftype in self._field_defs:")
    lines.append(f"      if offset + size <= len(data):")
    lines.append(f"        raw = data[offset:offset+size]")
    if spec.endianness == "big":
      lines.append(f"        val = int.from_bytes(raw, 'big')")
    else:
      lines.append(f"        val = int.from_bytes(raw, 'little')")
    lines.append(f"        result[name] = val")
    lines.append(f"        setattr(self, name, val)")
    lines.append(f"    if len(data) > self.header_size:")
    lines.append(f"      self.payload = data[self.header_size:]")
    lines.append(f"      result['payload'] = self.payload.hex()")
    lines.append(f"    return result")
    lines.append(f"")

    # Build message method
    lines.append(f"  def build_message(self, **kwargs) -> bytes:")
    lines.append(f"    \"\"\"Construct a protocol message from field values.\"\"\"")
    lines.append(f"    buf = bytearray()")
    for f in spec.fields:
      lines.append(f"    {f.name}_val = kwargs.get('{f.name}', 0)")
      if spec.endianness == "big":
        lines.append(f"    buf.extend({f.name}_val.to_bytes({f.size}, 'big'))")
      else:
        lines.append(f"    buf.extend({f.name}_val.to_bytes({f.size}, 'little'))")
    lines.append(f"    payload = kwargs.get('payload', b'')")
    lines.append(f"    if isinstance(payload, str):")
    lines.append(f"      payload = payload.encode()")
    lines.append(f"    # Auto-update length field if present")
    if spec.length_field:
      lf = spec.length_field
      lines.append(f"    total_len = len(buf) + len(payload)")
      lines.append(f"    length_bytes = total_len.to_bytes({lf.size}, '{spec.endianness}')")
      lines.append(f"    buf[{lf.offset}:{lf.offset + lf.size}] = length_bytes")
    lines.append(f"    return bytes(buf) + payload")
    lines.append(f"")

    # Send / recv
    lines.append(f"  def send(self, message: bytes) -> int:")
    lines.append(f"    \"\"\"Send a message and return bytes sent.\"\"\"")
    lines.append(f"    if not self.sock:")
    lines.append(f"      self.connect()")
    lines.append(f"    return self.sock.send(message)")
    lines.append(f"")
    lines.append(f"  def recv(self, bufsize=4096) -> bytes:")
    lines.append(f"    \"\"\"Receive a response.\"\"\"")
    lines.append(f"    if not self.sock:")
    lines.append(f"      raise ConnectionError('Not connected')")
    lines.append(f"    return self.sock.recv(bufsize)")
    lines.append(f"")
    lines.append(f"  def close(self):")
    lines.append(f"    \"\"\"Close the connection.\"\"\"")
    lines.append(f"    if self.sock:")
    lines.append(f"      self.sock.close()")
    lines.append(f"      self.sock = None")
    lines.append(f"")

    # Exploit primitives
    if exploit_primitives:
      lines.extend(self._synthesise_exploit_primitives(spec))
    lines.append(f"")

    # Convenience wrapper for message types
    if spec.message_types:
      lines.append(f"  # Known message types")
      for val, name in sorted(spec.message_types.items()):
        lines.append(f"  def send_{name}(self, **kwargs) -> Optional[bytes]:")
        lines.append(f"    \"\"\"Send a '{name}' ({val}) message.\"\"\"")
        if spec.type_field:
          tf = spec.type_field
          lines.append(f"    msg = self.build_message({tf.name}={val}, **kwargs)")
        else:
          lines.append(f"    msg = self.build_message(**kwargs)")
        lines.append(f"    self.send(msg)")
        lines.append(f"    return self.recv()")
        lines.append(f"")

    return "\n".join(lines)

  def _synthesise_exploit_primitives(self, spec: ProtocolSpec) -> List[str]:
    """Generate exploit primitives: fuzzing, overflow, injection."""
    lines = []
    lines.append(f"  # ── Exploit primitives ──")
    lines.append(f"")

    # Fuzzing
    lines.append(f"  def fuzz_field(self, field_name: str, iterations: int = 100):")
    lines.append(f"    \"\"\"Fuzz a single field with random values and observe responses.\"\"\"")
    lines.append(f"    import random")
    lines.append(f"    results = []")
    lines.append(f"    field_def = None")
    lines.append(f"    for fd in self._field_defs:")
    lines.append(f"      if fd[0] == field_name:")
    lines.append(f"        field_def = fd")
    lines.append(f"        break")
    lines.append(f"    if field_def is None:")
    lines.append(f"      raise ValueError(f'Unknown field: {{field_name}}')")
    lines.append(f"    _, offset, size, _ = field_def")
    lines.append(f"    max_val = (1 << (size * 8)) - 1")
    lines.append(f"    for _ in range(iterations):")
    lines.append(f"      fuzz_val = random.randint(0, max_val)")
    lines.append(f"      msg = self.build_message(**{{field_name: fuzz_val}})")
    lines.append(f"      self.send(msg)")
    lines.append(f"      try:")
    lines.append(f"        resp = self.recv()")
    lines.append(f"        results.append({{'value': fuzz_val, 'response_len': len(resp) if resp else 0, 'response': resp.hex()[:64] if resp else ''}})")
    lines.append(f"      except Exception as e:")
    lines.append(f"        results.append({{'value': fuzz_val, 'error': str(e)}})")
    lines.append(f"    return results")
    lines.append(f"")

    # Buffer overflow
    lines.append(f"  def overflow_payload(self, target_field: str, fill_byte: int = 0x41) -> bytes:")
    lines.append(f"    \"\"\"Generate a buffer-overflow payload targeting a field.\"\"\"")
    lines.append(f"    sizes = [64, 128, 256, 512, 1024, 2048, 4096]")
    lines.append(f"    payloads = []")
    lines.append(f"    for size in sizes:")
    lines.append(f"      overflow = bytes([fill_byte]) * size")
    lines.append(f"      payloads.append(self.build_message(**{{target_field: 0}}, payload=overflow))")
    lines.append(f"    return b''.join(payloads)")
    lines.append(f"")

    # Injection payload
    lines.append(f"  def inject_payload(self, injection: str, target_field: str = 'payload') -> bytes:")
    lines.append(f"    \"\"\"Craft a message with an injection payload.\"\"\"")
    lines.append(f"    if isinstance(injection, str):")
    lines.append(f"      injection = injection.encode()")
    lines.append(f"    return self.build_message(payload=injection)")
    lines.append(f"")

    # Checksum recalculation hint
    if spec.checksum_field:
      lines.append(f"  def recalc_checksum(self, data: bytearray) -> None:")
      lines.append(f"    \"\"\"Recalculate and update the checksum field.\"\"\"")
      lines.append(f"    cs_field = self._field_defs[{spec.fields.index(spec.checksum_field)}]")
      lines.append(f"    _, offset, size, _ = cs_field")
      lines.append(f"    # Zero out checksum before calculation")
      lines.append(f"    for i in range(offset, offset + size):")
      lines.append(f"      data[i] = 0")
      lines.append(f"    # Simple XOR checksum (override for real CRC)")
      lines.append(f"    cs = 0")
      lines.append(f"    for b in data:")
      lines.append(f"      cs ^= b")
      lines.append(f"    cs_bytes = cs.to_bytes(size, '{spec.endianness}')")
      lines.append(f"    for i, b_val in enumerate(cs_bytes):")
      lines.append(f"      data[offset + i] = b_val")
      lines.append(f"")

    # Type confusion
    lines.append(f"  def type_confusion(self, target_type: int) -> bytes:")
    lines.append(f"    \"\"\"Craft a message with an unexpected type value.\"\"\"")
    if spec.type_field:
      tf = spec.type_field
      lines.append(f"    return self.build_message({tf.name}=target_type)")
    else:
      lines.append(f"    return self.build_message(payload=b'\\\\x00' * 16)")
    lines.append(f"")

    return lines

  # ── Tool Validation ────────────────────────────────────────────────────────

  def validate_tool(self, tool_code: str,
                    test_cases: Optional[List[Dict[str, Any]]] = None) -> Dict[str, Any]:
    """Sandbox-test the generated tool against test cases.

    If no test cases are provided, a basic syntax and safety check is performed
    plus a smoke test with sample data derived from the protocol spec.

    Args:
      tool_code: The generated Python source code.
      test_cases: Optional list of test case dicts.

    Returns:
      Validation results dict with 'passed', 'failed', 'errors', 'total', 'details'.
    """
    if test_cases is None:
      test_cases = self._derive_test_cases(tool_code)

    results = self._validator.validate(tool_code, test_cases)
    logger.info("swce: tool validation complete: %d passed, %d failed, %d errors of %d total",
                 results["passed"], results["failed"], results["errors"], results["total"])
    return results

  def _derive_test_cases(self, tool_code: str) -> List[Dict[str, Any]]:
    """Derive basic smoke-test cases from the tool's own field definitions."""
    test_cases = []

    # Extract field definitions from the generated code
    field_pattern = re.findall(
      r"\('(\w+)',\s*(\d+),\s*(\d+),\s*'(\w+)'\)",
      tool_code,
    )

    if not field_pattern:
      return test_cases

    # Build a valid-looking message from field defaults
    header_bytes = bytearray()
    expected = {}
    for name, offset_str, size_str, ftype in field_pattern:
      offset = int(offset_str)
      size = int(size_str)
      # Pad to reach offset
      while len(header_bytes) < offset:
        header_bytes.append(0)
      if ftype == "magic":
        val = 0x01
        header_bytes.extend(val.to_bytes(size, "big"))
        expected[name] = val
      elif ftype == "type":
        val = 1
        header_bytes.extend(val.to_bytes(size, "big"))
        expected[name] = val
      elif ftype == "length":
        val = len(header_bytes) + size + 4  # header + 4-byte fake payload
        header_bytes.extend(val.to_bytes(size, "big"))
        expected[name] = val
      else:
        val = 0
        header_bytes.extend(val.to_bytes(size, "big"))
        expected[name] = val

    # Add a small payload
    payload = b"\x00\x01\x02\x03"
    test_message = bytes(header_bytes) + payload

    test_cases.append({
      "name": "smoke_test_valid",
      "input": test_message,
      "expected": expected,
    })

    # Empty message test
    test_cases.append({
      "name": "edge_case_empty",
      "input": b"",
      "expected": {"error": "data too short"},
    })

    return test_cases

  # ── Tool Deployment ────────────────────────────────────────────────────────

  def deploy_tool(self, tool_code: str, tool_name: str,
                  mission_id: str = "") -> GeneratedTool:
    """Add a generated tool to the PhantomStrike arsenal.

    Writes the tool to plugins/tools/generated/<tool_name>/tool.py and
    registers it so agents can discover and invoke it.

    Args:
      tool_code: The generated Python source.
      tool_name: Name for the tool (used as the directory and module name).
      mission_id: Optional mission this tool was created for.

    Returns:
      GeneratedTool with file_path and deployed=True.
    """
    tool_dir = self._arsenal_dir / tool_name
    tool_dir.mkdir(parents=True, exist_ok=True)

    # Write the tool
    tool_file = tool_dir / "tool.py"
    tool_file.write_text(tool_code, encoding="utf-8")

    # Write __init__.py so it can be imported
    init_file = tool_dir / "__init__.py"
    if not init_file.exists():
      init_file.write_text(f'"""Auto-generated tool: {tool_name}"""\nfrom .tool import ProtocolClient\n', encoding="utf-8")

    # Write metadata manifest
    manifest = {
      "name": tool_name,
      "version": 1,
      "description": f"Auto-generated protocol tool for {tool_name}",
      "category": "generated",
      "generated_by": "swce",
      "deployed_at": datetime.now(timezone.utc).isoformat(),
      "mission_id": mission_id,
    }
    manifest_file = tool_dir / "manifest.json"
    manifest_file.write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    # Record in memory
    tool = GeneratedTool(
      tool_id=f"gen_{uuid.uuid4().hex[:12]}",
      tool_name=tool_name,
      tool_code=tool_code,
      file_path=str(tool_file),
      deployed=True,
      mission_id=mission_id,
      created_at=datetime.now(timezone.utc).isoformat(),
      checksum=hashlib.sha256(tool_code.encode()).hexdigest()[:16],
    )
    self._tools[tool_name] = tool

    logger.info("swce: deployed tool %s to %s", tool_name, tool_file)
    return tool

  # ── Tool Archival ──────────────────────────────────────────────────────────

  def archive_tool(self, tool_metadata: Dict[str, Any]) -> bool:
    """Persist tool metadata to the database.

    Stores version, mission_id, success_rate, and the generated code so
    the tool can be retrieved and reused in future operations.

    Args:
      tool_metadata: Dict with keys matching ToolArchiveRecord fields.
                     At minimum: tool_id, tool_name, tool_code.

    Returns:
      True if archived successfully, False otherwise.
    """
    if self._db is None:
      logger.warning("swce: no DB available, skipping archive for %s",
                      tool_metadata.get("tool_name", "unknown"))
      return False

    try:
      tool_id = tool_metadata.get("tool_id", f"gen_{uuid.uuid4().hex[:12]}")
      tool_name = tool_metadata.get("tool_name", "unknown_tool")
      protocol_name = tool_metadata.get("protocol_name",
                                         tool_metadata.get("protocol_spec", {}).get("protocol_name", "unknown"))
      version = tool_metadata.get("version", 1)
      mission_id = tool_metadata.get("mission_id", "")
      success_rate = tool_metadata.get("success_rate", 0.0)
      tool_code = tool_metadata.get("tool_code", "")
      checksum = tool_metadata.get("checksum",
                                    hashlib.sha256(tool_code.encode()).hexdigest()[:16] if tool_code else "")
      now = datetime.now(timezone.utc).isoformat()

      # Store in exploit_generations table (reuse for generated tools)
      self._db.create_exploit_generation(
        session_id=mission_id,
        cve_id="",
        vuln_type="protocol_tool",
        exploit_code=tool_code,
        target_info=json.dumps({
          "tool_name": tool_name,
          "protocol_name": protocol_name,
          "version": version,
          "checksum": checksum,
          "success_rate": success_rate,
          "tool_id": tool_id,
        }),
        language="python",
        evasion_applied="none",
      )

      logger.info("swce: archived tool %s (id=%s, v%d, success_rate=%.2f) to DB",
                   tool_name, tool_id, version, success_rate)
      return True

    except Exception as exc:
      logger.error("swce: failed to archive tool %s: %s",
                    tool_metadata.get("tool_name", "unknown"), exc)
      return False

  # ── Tool Lookup ────────────────────────────────────────────────────────────

  def get_tool(self, tool_name: str) -> Optional[GeneratedTool]:
    """Retrieve a deployed tool by name."""
    return self._tools.get(tool_name)

  def list_tools(self) -> List[Dict[str, Any]]:
    """List all deployed generated tools."""
    return [
      {
        "tool_name": t.tool_name,
        "tool_id": t.tool_id,
        "version": t.version,
        "deployed": t.deployed,
        "validated": t.validated,
        "created_at": t.created_at,
        "mission_id": t.mission_id,
      }
      for t in self._tools.values()
    ]

  def get_arsenal_stats(self) -> Dict[str, Any]:
    """Return summary statistics about the generated tool arsenal."""
    total_tools = len(self._tools)
    deployed = sum(1 for t in self._tools.values() if t.deployed)
    validated = sum(1 for t in self._tools.values() if t.validated)
    return {
      "total_generated": total_tools,
      "deployed": deployed,
      "validated": validated,
      "arsenal_dir": str(self._arsenal_dir),
    }
