export const INSTALL_HINTS: Record<string, string> = {
  eaphammer:         'sudo apt install eaphammer',
  nmap:              'sudo apt install nmap',
  masscan:           'sudo apt install masscan',
  rustscan:          'cargo install rustscan  # or: sudo apt install rustscan',
  autorecon:         'pip3 install autorecon',
  gobuster:          'sudo apt install gobuster',
  ffuf:              'sudo apt install ffuf',
  feroxbuster:       'sudo apt install feroxbuster',
  dirb:              'sudo apt install dirb',
  dirsearch:         'pip3 install -r requirements.txt',
  nikto:             'sudo apt install nikto',
  nuclei:            'go install github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest',
  sqlmap:            'sudo apt install sqlmap',
  wpscan:            'sudo apt install wpscan  # or: gem install wpscan',
  hydra:             'sudo apt install hydra',
  john:              'sudo apt install john',
  hashcat:           'sudo apt install hashcat',
  medusa:            'sudo apt install medusa',
  patator:           'sudo apt install patator',
  hashid:            'pip3 install hashid',
  ophcrack:          'sudo apt install ophcrack',
  amass:             'sudo apt install amass',
  subfinder:         'go install github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest',
  fierce:            'pip3 install fierce',
  dnsenum:           'sudo apt install dnsenum',
  theHarvester:      'sudo apt install theharvester',
  sherlock:          'sudo apt install sherlock',
  whois:             'sudo apt install whois',
  httpx:             'go install github.com/projectdiscovery/httpx/cmd/httpx@latest',
  katana:            'go install github.com/projectdiscovery/katana/cmd/katana@latest',
  hakrawler:         'go install github.com/hakluke/hakrawler@latest',
  gau:               'go install github.com/lc/gau/v2/cmd/gau@latest',
  waybackurls:       'go install github.com/tomnomnom/waybackurls@latest',
  wafw00f:           'pip3 install wafw00f',
  dalfox:            'go install github.com/hahwul/dalfox/v2@latest',
  jaeles:            'go install github.com/jaeles-project/jaeles@latest',
  arjun:             'pip3 install arjun',
  paramspider:       'pip3 install paramspider',
  x8:                'cargo install x8',
  gdb:               'sudo apt install gdb',
  radare2:           'sudo apt install radare2',
  binwalk:           'sudo apt install binwalk',
  ROPgadget:         'pip3 install -r requirements.txt',
  checksec:          'sudo apt install checksec  # or: pip3 install checksec',
  objdump:           'sudo apt install binutils',
  ghidra:            'sudo apt install ghidra  # or download from ghidra.re',
  pwntools:          'pip3 install -r requirements.txt',
  ropper:            'pip3 install ropper',
  angr:              'pip3 install -r requirements.txt',
  pwninit:           'cargo install pwninit',
  'one-gadget':      'pip3 install -r requirements.txt',
  'libc-database':   'https://github.com/niklasb/libc-database',
  vol:               'pip3 install -r requirements.txt',
  volatility:        'pip3 install -r requirements.txt',
  steghide:          'sudo apt install steghide',
  foremost:          'sudo apt install foremost',
  exiftool:          'sudo apt install libimage-exiftool-perl',
  strings:           'sudo apt install binutils',
  xxd:               'sudo apt install xxd',
  photorec:          'sudo apt install testdisk',
  testdisk:          'sudo apt install testdisk',
  scalpel:           'sudo apt install scalpel',
  zsteg:             'gem install zsteg',
  outguess:          'sudo apt install outguess',
  prowler:           'pip3 install prowler',
  'scout-suite':     'pip3 install scoutsuite',
  trivy:             'sudo apt install trivy',
  'kube-hunter':     'pip3 install kube-hunter',
  'kube-bench':      'https://aquasecurity.github.io/kube-bench/latest/installation/',
  'docker-bench-security': 'https://github.com/docker/docker-bench-security',
  checkov:           'pip3 install -r requirements.txt',
  terrascan:         'brew install terrascan  # or download from github.com/tenable/terrascan',
  clair:             'docker pull quay.io/projectquay/clair',
  msfconsole:        'sudo apt install metasploit-framework',
  msfvenom:          'sudo apt install metasploit-framework',
  searchsploit:      'sudo apt install exploitdb',
  smbmap:            'pip3 install smbmap',
  enum4linux:        'sudo apt install enum4linux',
  'enum4linux-ng':   'pip3 install enum4linux-ng',
  nbtscan:           'sudo apt install nbtscan',
  rpcclient:         'sudo apt install samba-common-bin',
  responder:         'sudo apt install responder',
  nxc:               'pip3 install netexec',
  'evil-winrm':      'gem install evil-winrm',
  'airmon-ng':       'sudo apt install aircrack-ng',
  'aircrack-ng':     'sudo apt install aircrack-ng',
  'airodump-ng':     'sudo apt install aircrack-ng',
  'aireplay-ng':     'sudo apt install aircrack-ng',
  'airbase-ng':      'sudo apt install aircrack-ng',
  'airdecap-ng':     'sudo apt install aircrack-ng',
  kismet:            'sudo apt install kismet',
  wireshark:         'sudo apt install wireshark',
  tshark:            'sudo apt install tshark',
  tcpdump:           'sudo apt install tcpdump',
  wifite:            'sudo apt install wifite',
  bettercap:         'sudo apt install bettercap',
  mdk4:              'sudo apt install mdk4',
  bbot:              'pip3 install -r requirements.txt',
  curl:              'sudo apt install curl',
  httpie:            'pip3 install httpie',
  anew:              'go install -v github.com/tomnomnom/anew@latest',
  qsreplace:         'go install -v github.com/tomnomnom/qsreplace@latest',
  uro:               'pip3 install -r requirements.txt',
  'graphql-scanner': 'npm install -g graphql-voyager',
  wfuzz:             'pip3 install wfuzz',
  dotdotpwn:         'sudo apt install dotdotpwn',
  xsser:             'sudo apt install xsser',
  commix:            'sudo apt install commix',
  tplmap:            'git clone https://github.com/epinna/tplmap',
  nosqlmap:          'git clone https://github.com/codingo/NoSQLMap',
  whatweb:           'sudo apt install whatweb',
  testssl:           'sudo apt install testssl.sh',
  sslscan:           'sudo apt install sslscan',
  sslyze:            'pip3 install sslyze',
  'recon-ng':        'sudo apt install recon-ng',
  maltego:           'Download from maltego.com',
  spiderfoot:        'sudo apt install spiderfoot',
  'social-analyzer': 'pip3 install -r requirements.txt',
  sleuthkit:         'sudo apt install sleuthkit',
  autopsy:           'sudo apt install autopsy',
  'bulk_extractor':  'sudo apt install bulk-extractor',
  'hashcat-utils':   'sudo apt install hashcat-utils',
  cloudmapper:       'https://github.com/duo-labs/cloudmapper',
  vulnx:             'go install github.com/projectdiscovery/cvemap/cmd/vulnx@latest',
  falco:             'https://falco.org/docs/setup/packages/#install-with-apt',
  ldapdomaindump:    'sudo apt install python3-ldapdomaindump',
  sublist3r:         'sudo apt install sublist3r',
  parsero:           'sudo apt install parsero',
  joomscan:          'sudo apt install joomscan',
  interactsh:        'go install -v github.com/projectdiscovery/interactsh/cmd/interactsh-client@latest',
  schemathesis:      'pipx install schemathesis  # or: pip install schemathesis',
  hurl:              'sudo apt install hurl',
  assetfinder:       'sudo apt install assetfinder',
  shuffledns:        'sudo apt-get install -y massdns; go install -v github.com/projectdiscovery/shuffledns/cmd/shuffledns@latest',
  massdns:           'sudo apt install massdns',
  gospider:          'sudo apt install gospider',
  dig:               'sudo apt install bind9-dnsutils',

}

export function installHint(name: string): string {
  return INSTALL_HINTS[name] ?? `# check project docs for exact install`
}
