"""
server_core/orchestrator/recon_agent.py

Reconnaissance specialist agent.

Uses OSINT tools (Shodan, phone tracer, email breach, social search,
Google dork, WHOIS, DNS enumeration). Works standalone with pattern-
matching fallback when an LLM is unavailable.

Input: target identifier (IMEI, IP, domain, email, phone).
Output: comprehensive target profile.
"""

import json
import logging
import time
from typing import Any, Dict, List, Optional, Tuple

from server_core import ModernVisualEngine

logger = logging.getLogger(__name__)


class ReconAgent:
    """Reconnaissance specialist — builds a comprehensive target profile.

    Capabilities (simulated tool calls; replace stubs with real integrations):
      - IMEI lookup → device make/model, carrier, country.
      - WHOIS → registrant, NS, dates.
      - DNS enumeration → A, AAAA, MX, NS, CNAME, TXT, SOA.
      - Shodan → open ports, services, banners, CPEs.
      - Email breach → HaveIBeenPwned, DeHashed style lookups.
      - Google dork → site:, intitle:, inurl:, filetype: queries.
      - Social search → username enumeration across platforms.
      - Port scanning → nmap fingerprint.
    """

    AGENT_NAME = "recon"

    # Simulated tool registry — maps tool name to handler method
    TOOL_HANDLERS: Dict[str, callable] = {}

    def __init__(self, llm_client: Any = None):
        self._llm = llm_client
        self._register_tools()

    def _register_tools(self) -> None:
        """Map tool names to instance methods for dispatch."""
        self.TOOL_HANDLERS = {
            "phone_tracer": self._trace_phone,
            "imei_parser": self._parse_imei,
            "gsm_lookup": self._gsm_lookup,
            "carrier_lookup": self._carrier_lookup,
            "whois": self._whois_lookup,
            "dns_enum": self._dns_enum,
            "shodan": self._shodan_scan,
            "email_breach": self._email_breach_check,
            "google_dork": self._google_dork,
            "social_search": self._social_search,
            "nmap": self._nmap_scan,
            "masscan": self._nmap_scan,  # alias
            "rustscan": self._nmap_scan,  # alias
            "hss_query": self._hss_query,
            "ss7_scanner": self._ss7_scan,
            "sql_ping": self._sql_ping,
            "port_scan": self._nmap_scan,
            "report_builder": lambda *a, **kw: {"report": "Generated by ReconAgent"},
            "markdown_renderer": lambda *a, **kw: {"report": "Generated by ReconAgent"},
        }

    # ------------------------------------------------------------------
    # Main entry point
    # ------------------------------------------------------------------

    def execute(self, phase: Dict[str, Any], context: Dict[str, Any]) -> Dict[str, Any]:
        """Run reconnaissance for the given phase.

        Args:
            phase: Phase spec with id, tools_needed, parameters, etc.
            context: Shared memory context from previous agents.

        Returns:
            Dict with success, data, error, elapsed_seconds.
        """
        start = time.time()
        phase_id = phase.get("id", "unknown")
        tools = phase.get("tools_needed", [])
        params = phase.get("parameters", {})
        extracted = params.get("extracted_targets", {})

        logger.info(
            "%s",
            ModernVisualEngine.create_section_header(
                f"RECON AGENT — {phase.get('label', phase_id)}", "🔍", "NEON_BLUE"
            ),
        )

        findings: Dict[str, Any] = {}
        errors: List[str] = []

        # Determine primary target
        target = self._resolve_target(extracted, params)
        if not target:
            elapsed = time.time() - start
            return {
                "success": False,
                "error": "No target identifier found in parameters or context",
                "elapsed_seconds": round(elapsed, 2),
            }

        logger.info("Recon target: %s", target)

        # Execute each requested tool
        for tool in tools:
            try:
                handler = self.TOOL_HANDLERS.get(tool)
                if handler is None:
                    logger.warning("Unrecognised recon tool '%s' — skipped", tool)
                    findings[tool] = {"error": f"Tool '{tool}' not available"}
                    continue

                logger.info("Running recon tool: %s", tool)
                result = handler(target, params, context)
                findings[tool] = result

                # Enrich context with discovered IPs / domains
                if isinstance(result, dict):
                    if result.get("ip"):
                        context.setdefault("discovered_ips", []).append(result["ip"])
                    if result.get("domain"):
                        context.setdefault("discovered_domains", []).append(result["domain"])

            except Exception as exc:
                msg = f"Tool '{tool}' failed: {str(exc)}"
                logger.exception(msg)
                errors.append(msg)
                findings[tool] = {"error": str(exc)}

        elapsed = time.time() - start
        success = len(errors) == 0

        return {
            "success": success,
            "data": findings,
            "error": "; ".join(errors) if errors else None,
            "elapsed_seconds": round(elapsed, 2),
            "target": target,
        }

    # ------------------------------------------------------------------
    # Target resolution
    # ------------------------------------------------------------------

    def _resolve_target(self, extracted: Dict[str, Any], params: Dict[str, Any]) -> Optional[str]:
        """Pull the best target string from extracted data or params."""
        # Priority: explicit target param > IMEI > IP > domain > email > URL > phone
        if params.get("target"):
            return params["target"]

        for ttype in ("imei", "ip", "domain", "email", "url", "phone"):
            data = extracted.get(ttype)
            if data:
                if isinstance(data, dict):
                    return data.get("value") or (data.get("values", [None])[0] if isinstance(data.get("values"), list) else None)
                return str(data[0]) if isinstance(data, list) else str(data)

        return None

    # ------------------------------------------------------------------
    # Tool handlers (stub implementations)
    # ------------------------------------------------------------------

    def _trace_phone(self, target: str, params: Dict, ctx: Dict) -> Dict[str, Any]:
        """Simulated phone number trace — IMEI-based device lookup."""
        return {
            "imei": target,
            "device_make": "Samsung",
            "device_model": "Galaxy S23 Ultra",
            "manufacturer": "Samsung Electronics",
            "os": "Android 14",
            "country": "US",
            "carrier": "T-Mobile",
            "first_seen": "2024-01-15",
            "last_seen": "2025-06-10",
            "status": "active",
            "note": "[STUB] Replace with real phone tracer integration",
        }

    def _parse_imei(self, target: str, params: Dict, ctx: Dict) -> Dict[str, Any]:
        """Parse IMEI to extract TAC (Type Allocation Code) and serial."""
        imei = target.strip()
        return {
            "imei": imei,
            "tac": imei[:8],
            "serial": imei[8:14],
            "luhn_digit": imei[-1] if len(imei) >= 15 else None,
            "reporting_body": "PTCRB" if imei[:2] == "35" else "GSMA",
            "note": "[STUB] IMEI parsed — no live DB hit",
        }

    def _gsm_lookup(self, target: str, params: Dict, ctx: Dict) -> Dict[str, Any]:
        """Simulated GSM infrastructure lookup."""
        return {
            "imei": target,
            "imsi": "310260123456789",
            "msisdn": "+12025551234",
            "msc": "MSC-ATL-01",
            "hlr": "HLR-ATL-PRIMARY",
            "network_type": "5G NSA",
            "roaming": False,
            "note": "[STUB] GSM lookup — SS7 integration placeholder",
        }

    def _carrier_lookup(self, target: str, params: Dict, ctx: Dict) -> Dict[str, Any]:
        """Simulated carrier info lookup."""
        return {
            "carrier": "T-Mobile USA",
            "mcc": "310",
            "mnc": "260",
            "country": "United States",
            "brand": "T-Mobile",
            "apn": "fast.t-mobile.com",
            "note": "[STUB] Carrier MNC/MCC resolved from local DB",
        }

    def _whois_lookup(self, target: str, params: Dict, ctx: Dict) -> Dict[str, Any]:
        """Simulated WHOIS lookup."""
        return {
            "domain": target,
            "registrar": "GoDaddy.com, LLC",
            "creation_date": "2020-03-15",
            "expiration_date": "2026-03-15",
            "name_servers": ["ns1.example.com", "ns2.example.com"],
            "registrant_org": "Example Corp",
            "registrant_country": "US",
            "note": "[STUB] WHOIS — integrate python-whois or RDAP",
        }

    def _dns_enum(self, target: str, params: Dict, ctx: Dict) -> Dict[str, Any]:
        """Simulated DNS enumeration."""
        return {
            "domain": target,
            "a_records": ["93.184.216.34"],
            "aaaa_records": ["2606:2800:220:1:248:1893:25c8:1946"],
            "mx_records": ["mail.example.com"],
            "ns_records": ["ns1.example.com", "ns2.example.com"],
            "cname_records": {"www": "example.com"},
            "txt_records": ["v=spf1 include:_spf.example.com ~all"],
            "soa": {"mname": "ns1.example.com", "rname": "admin.example.com"},
            "note": "[STUB] DNS — integrate dnspython",
        }

    def _shodan_scan(self, target: str, params: Dict, ctx: Dict) -> Dict[str, Any]:
        """Simulated Shodan lookup."""
        return {
            "ip": target,
            "ports": [22, 80, 443, 8080, 8443],
            "services": {
                "22": "OpenSSH 8.9p1",
                "80": "nginx/1.24.0",
                "443": "nginx/1.24.0 (TLS 1.3)",
            },
            "org": "Example Hosting LLC",
            "country": "US",
            "vulns": ["CVE-2023-44487 (HTTP/2 Rapid Reset)"],
            "note": "[STUB] Shodan — integrate shodan-python SDK",
        }

    def _email_breach_check(self, target: str, params: Dict, ctx: Dict) -> Dict[str, Any]:
        """Simulated email breach check."""
        return {
            "email": target,
            "breaches": ["Collection #1", "LinkedIn (2021)", "Adobe (2013)"],
            "paste_count": 3,
            "note": "[STUB] Breach check — integrate HIBP API v3",
        }

    def _google_dork(self, target: str, params: Dict, ctx: Dict) -> Dict[str, Any]:
        """Simulated Google dorking results."""
        dorks = [
            f"site:{target} filetype:pdf",
            f"site:{target} intitle:\"index of\"",
            f"site:{target} inurl:admin",
            f'"{target}" ext:sql | ext:sql.gz',
        ]
        return {
            "target": target,
            "dorks_executed": dorks,
            "hits": {
                dorks[0]: 12,
                dorks[1]: 3,
                dorks[2]: 1,
                dorks[3]: 0,
            },
            "note": "[STUB] Google dork — integrate with custom search API or scrape",
        }

    def _social_search(self, target: str, params: Dict, ctx: Dict) -> Dict[str, Any]:
        """Simulated social media username search."""
        platforms = {
            "github": {"found": True, "url": f"https://github.com/{target}"},
            "twitter": {"found": True, "url": f"https://twitter.com/{target}"},
            "linkedin": {"found": True, "url": f"https://linkedin.com/in/{target}"},
            "instagram": {"found": False, "url": None},
            "reddit": {"found": True, "url": f"https://reddit.com/user/{target}"},
        }
        return {
            "username": target,
            "platforms": platforms,
            "note": "[STUB] Social search — integrate sherlock or maigret",
        }

    def _nmap_scan(self, target: str, params: Dict, ctx: Dict) -> Dict[str, Any]:
        """Simulated nmap / port scan."""
        return {
            "target": target,
            "command": f"nmap -sV -sC -O {target}",
            "open_ports": {
                22: {"service": "ssh", "version": "OpenSSH 8.9p1"},
                80: {"service": "http", "version": "nginx 1.24.0"},
                443: {"service": "https", "version": "nginx 1.24.0"},
                3306: {"service": "mysql", "version": "MySQL 8.0.33"},
            },
            "os_guess": "Linux 5.15 (Ubuntu 22.04)",
            "uptime": "124 days",
            "note": "[STUB] Port scan — integrate python-nmap",
        }

    def _hss_query(self, target: str, params: Dict, ctx: Dict) -> Dict[str, Any]:
        """Simulated HSS (Home Subscriber Server) query."""
        return {
            "imei": target,
            "subscription_status": "active",
            "apn_config": "default",
            "qos_profile": "QCI-9",
            "note": "[STUB] HSS query — telecom API placeholder",
        }

    def _ss7_scan(self, target: str, params: Dict, ctx: Dict) -> Dict[str, Any]:
        """Simulated SS7 network scan."""
        return {
            "imei": target,
            "ss7_reachable": True,
            "gt_routing": {"pc": 12345, "ssn": 8},
            "note": "[STUB] SS7 scan — signaling firewall/GT check placeholder",
        }

    def _sql_ping(self, target: str, params: Dict, ctx: Dict) -> Dict[str, Any]:
        """Simulated database ping."""
        return {
            "host": target,
            "db_type": "mysql",
            "version": "8.0.33",
            "tcp_port": 3306,
            "note": "[STUB] DB ping — integrate mysql-ping / pg-ping",
        }
